### ISSUE TITLE
指令

### ISSUE THREAD

**Issue by mentlesoul** [alex3236/joinMOTD_Plus#1]
如果欢迎词被聊天消息顶上去了找不到了，怎么重新加载或者拉取服务器列表

**Comment by alex3236** [comment]
这。。插件的本意只是在 **玩家进入服务器时** 提供欢迎消息和快捷的服务器切换列表。不过这个建议也有点意思，到时候改进一下

**Comment by alex3236** [comment]
version 2.2.0
