### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by TaiChi01** [alex3236/joinMOTD_Plus#2]
!!motd以及!!server两条命令均无反应
MCDR为1.5.1

**Comment by alex3236** [comment]
理论在 [6b96a97](https://github.com/eagle3236/joinMOTD_Plus/commit/6b96a9759d23806180164f529dbe3373f8dc0b84) 中修复，请检查（最近在忙一直没有上服务端测试，可能还有 BUG 不好意思）
~~近期会再次重构代码，敬请期待 :)~~
