### ISSUE TITLE
mcdr2.0

### ISSUE THREAD

**Issue by ghost** [alex3236/joinMOTD_Plus#4]
mcdr2.0!!!!!!!

**Comment by alex3236** [comment]
理论上可以直接兼容。正在大改，可以等等(

**Comment by ghost** [comment]
> 理论上可以直接兼容。正在大改，可以等等(

api不行的樣子JSON api

**Comment by alex3236** [comment]
> > 理论上可以直接兼容。正在大改，可以等等(
> 
> api不行的樣子JSON api

确实（

**Comment by ghost** [comment]
> > > 理论上可以直接兼容。正在大改，可以等等(
> > 
> > 
> > api不行的樣子JSON api
> 
> 确实（

**Comment by alex3236** [comment]
？

**Comment by ghost** [comment]
> ？

啊这，要留？我是已经问到我想知道的了（dog）
