### ISSUE TITLE
您好，服务器添加该插件以后进入服务器时无法自动显示

### ISSUE THREAD

**Issue by LinkNoel** [alex3236/joinMOTD_Plus#6]
只有在输入!!motd后才会显示配置文件中的内容，请问这是由于什么原因导致的呢？

**Comment by alex3236** [comment]
### 请提供更多信息
- MCDR 版本、插件版本
- 相关日志
- ...

**Comment by LinkNoel** [comment]
MCDR版本：是使用pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple mcdreforged 命令直接获取的，应该是最新版
插件版本：join_motd_plus_3.1.0.mcdr
MC版本：1.12.2，使用Forge+Sponge的服务端
Forge版本：forge-1.12.2-14.23.5.2855-installer.jar
SpongeForge版本：spongeforge-1.12.2-2838-7.3.1-RC4082.jar
这段时间我自己测试了一下，在仅安装Forge的情况下，MOTD可以正常显示，在添加SpongeForge后MOTD就无法进服显示了，可通过!!motd显示，因此想问一下大佬是什么原因导致的，不过这个不是什么大问题，只是想问一下。谢谢大佬！

**Comment by alex3236** [comment]
判断是玩家加入服务器的控制台消息被修改或取消，导致 MCDR 未正确处理玩家加入服务器事件。
可以自己魔改下 handler 或者给 MCDR 提个 PR/issue
若仍有问题请附加更多信息w
